language: php

php:
    - 7.1
    - 7.2
    - 7.3

matrix:
    include:
        - php: 7.1
          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"

before_script:
    - composer update --prefer-dist --no-interaction ${COMPOSER_FLAGS}

script:
    - php vendor/bin/phpunit tests/Unit
    - php vendor/bin/phpcs ./src ./tests

after_success:
    - bash <(curl -s https://codecov.io/bash)
